name: Meson Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-meson:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++, msys2-gcc]
        ffmpeg_configure_args: ["--disable-shared --enable-static", "--disable-static --enable-shared"]
        ffms2_default_library: [static, shared, both]
        exclude:
          # ---------- Linux ----------
          - os: ubuntu-latest
            compiler: msys2-gcc

          # ---------- macOS ----------
          - os: macos-latest
            compiler: g++
          - os: macos-latest
            compiler: msys2-gcc

          # ---------- Windows ----------
          - os: windows-latest
            compiler: g++
          - os: windows-latest
            compiler: clang++

    name: "Test (${{ matrix.os }}, ${{ matrix.cc }}, ffmpeg=${{ matrix.ffmpeg_configure_args }}, ffms2=${{ matrix.ffms2_default_library }})"
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake wget nasm meson

      - name: Install deps (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install autoconf automake libtool wget meson

      - name: Setup MSYS2 (MINGW64)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-ca-certificates
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-toolchain

      - name: Download ffmpeg
        run: wget https://ffmpeg.org/releases/ffmpeg-8.0.tar.xz

      - name: Extract ffmpeg
        run: tar xf ffmpeg-8.0.tar.xz

      - name: Create build_dependencies directory
        run: mkdir "build_dependencies"

      - name: Configure ffmpeg
        run: |
          ABS_BUILD_PATH="$(realpath "$(pwd)/../build_dependencies")"
          ./configure ${{ matrix.ffmpeg_configure_args }} --enable-pic --prefix="$ABS_BUILD_PATH/usr/local"
        working-directory: ffmpeg-8.0

      - name: Build ffmpeg
        run: make
        working-directory: ffmpeg-8.0

      - name: Install ffmpeg
        run: make install
        working-directory: ffmpeg-8.0

      - name: Configure with Meson
        run: >
          meson setup builddir
          -Ddefault_library=${{ matrix.ffms2_default_library }}
          -Dtest=enabled
          --pkg-config-path="$(pwd)/build_dependencies/usr/local/lib/pkgconfig"

      - name: Build
        run: meson compile -C builddir --verbose

      - name: Run tests
        run: meson test -C builddir --verbose
